### ISSUE TITLE
about heartbeat

### ISSUE THREAD

**Issue by wulinwulin76** [CopernicaMarketingSoftware/AMQP-CPP#113]
RabbitMQ uses a heartbeat to detect dead connection. 
Is there a parameter in the AMQP-CPP to set the hearbeat interval? When there is no publish for more than 3*hearbeat seconds, will get the error: "connection reset by peer".
The configuration of rabbit server's heartbeat is: 60.

In my code, the ev_run is called every 1 milliseconds:   

```
void MQTopicConsume::slotTimerEventRunEv()
{
    auto *loop = EV_DEFAULT;
    ev_run(loop, EVRUN_NOWAIT); //NOWAIT
}
```

To avoid the reset error,  another piece of code is run every 10 seconds:
```
void MQTopicConsume::slotTimerEventSimuHeartBeat()
{
    if(channel&&channel->connected())
        channel->publish(exchangeName,"Simu.HeartBeat","Hello to Broker"); //avoid reset caused by missing heartbeat
}
```

**Comment by EmielBruijntjes** [comment]
I have one answer, and one good advise.

The answer: yes, you can change the heartbeat interval, or even disable heartbeats. If you override the tcpconnectionhandler class that you pass to the tcpconnection constructor, you can implement/override a number of methods in it. One of them is the onNegotiate() method (if I remember correctly). This is a method that gets called on connection setup to negotiate the heartbeat interval. If you set it to zero, the heartbeats are completely disabled.

The advise: change the architecture of your application. The whole idea of an event loop is to run it continuously. You already seem to have a "slotTimerEventRunEv", so there must already be some kind of event loop in your app that triggers this timer. Why do you not utilize this event loop instead of creating a second libev based event loop that you only use for AMQP? Your current architecture seems wrong.
