### ISSUE TITLE
AMQP-CPP implementation in cpp (Visual studio 2017)

### ISSUE THREAD

**Issue by vikaschamp** [CopernicaMarketingSoftware/AMQP-CPP#151]
I have installed AMQP-CPP (rabbit mq library ) from NuGet package in visual studio 2017. But i am not able to implement correctly. Please suggest me some example to implement successfully .

I have already tried also these links :-

https://github.com/CopernicaMarketingSoftware/AMQP-CPP
https://github.com/RPG-18/rabbitmq-cpp-tutorials
https://github.com/hoxnox/examples.amqp-cpp
...
 Thanks in Advance

**Comment by fantastory** [comment]
Copernica does not build it on windows.
The nuget package is built on on vs2016 you should try rebuilding it from source.

**Comment by vikaschamp** [comment]
The nuget package is built on on vs2016 you should try rebuilding it from source = **i am not able to build**  .

**Comment by fantastory** [comment]
It must admit that it will require some work to port examples. In the unspecified long mean time I will hide that nuget package.

**Comment by vikaschamp** [comment]
The NuGet package  , AMQP-CPP library which i installed in vs 2017 that will not work ?
Is there any other option for windows to use your library rather than compiling on windows?

**Comment by fantastory** [comment]
I have created https://github.com/fantastory/AMQP-CPP/issues/2
Not to bother copernica with windows issues.

The visualstudio 2015 **binary** package AMQP-CPP-vc140 works for me and it should work even in vs2017. 
If not you would need to rebuild and probably modify some source. 
As a hint I would try boost versions instead of porting bsd sockets, but note that copernica has removed old boost adapter and replaced it with new one from a contributor.

You could also try other forks. I see there are some market as windows/visualstudio.

**Comment by vikaschamp** [comment]
I have installed rabbit mq in my system and erlang also .
When i am creating channel and queue using AMQP-CPP library then i am not able to connect.

I have wrote this code : My raabit mq id and pass is "finsoltech" & "pass123!".


	MyConnectionHandler my;
	// create a AMQP connection object
	AMQP::Connection connection(&my, AMQP::Login("finsoltech", "pass123!"), "/");

	// and create a channel
	AMQP::Channel channel(&connection);

	// use the channel object to call the AMQP method you like
	channel.declareExchange("my-exchange", AMQP::fanout);
	channel.declareQueue("my-queue");
	channel.bindQueue("my-exchange", "my-queue", "my-routing-key");

**Comment by vikaschamp** [comment]
Fixes #151

**Comment by EmielBruijntjes** [comment]
Closing this issue because we do not support Windows.
