### ISSUE TITLE
Frame size exceeded

### ISSUE THREAD

**Issue by Edgesystems** [CopernicaMarketingSoftware/AMQP-CPP#18]
I'm getting this in the consumer a couple times a day. Works perfectly for a couple of hours at a time.

RabbitMQ: 3.3.5
AMQP-CPP: v2.1.4
OS: Debian 7.6
g++: 4.7

# AMQP code: 
```
  // Global buffer
    std::vector<char> amqpBuffer;
    amqpBuffer.reserve( 66536 );

    while( this->m_run ) {
        try {
            // Internal buffer
            char buff[1024];

            // Read from socket (basically a class wrapper around the recv func which throws exceptions if read < 1)
            size_t read = this->amqpSocket->recv( buff, sizeof(buff) - 1 );

            // Insert into buffer
            amqpBuffer.insert( amqpBuffer.end(), buff, buff + read );

            // Let amqp parse
            size_t parsed = this->amqpAmiConnection->parse( amqpBuffer.data(), amqpBuffer.size() );

            if( parsed > 0 ) {
                std::vector<char>::iterator it = amqpBuffer.begin();

                amqpBuffer.erase( it, it + parsed );
            }
        } catch( const std::exception &e ) {
            std::cout << e.what() << std::endl;
            throw;
        } catch( ... ) {
            std::cout << "Received unknown exception." << std::endl;
            throw;
        }
    }
```

**Comment by martijnotto** [comment]
This exception indicates that the server sent a message that exceeds the maximum frame size, which is interesting since the server gets to choose the maximum frame size when the connection is established.

I have never encountered this bug myself, and we make heavy use of this library at Copernica. Since I cannot reproduce this issue myself, I have no idea what exactly goes wrong. It could be a bug in RabbitMQ (which I think unlikely) or it could be a bug in the AMQP library.

Perhaps you could make a wireshark trace? The interesting data to see is the Connection.Tune frame that AMQP sends and the reply we send to it (we should accept the servers parameters) and the actual frame that caused the exception (this should be the last frame received, as the connection should be closed immediately when this error occurs).

Could you tell me the maximum frame size the server selected (from the Connection.Tune frame) and the payload size of the offending frame? If the frame is indeed too big it would be a bug inside RabbitMQ and if not we have a bug inside the AMQP library.

**Comment by Edgesystems** [comment]
Actually, I think this was my mistake. I used another way of handling the buffer before (char array and a size_t counter which moved the pointer and used memcpy to move data to the beginning of the array). Later on when scp:ing the data to the server, I copied it to the wrong location resulting in executing the same old binary.

Seems to work now (have been for 3 days).
