### ISSUE TITLE
What is ChannelHandler?

### ISSUE THREAD

**Issue by willnige** [CopernicaMarketingSoftware/AMQP-CPP#19]
Your README refers to a ChannelHandler::onReturned() callback.  I can't find any reference to a channel handler in the source or an onReturned callback.  Can you please clarify what this refers to.
Thanks
Nigel

**Comment by EmielBruijntjes** [comment]
A ChannelHandler is an old interface that we used in one of the first AMQP-CPP function, more or less the same as the ConnectionHandler class. It had to be associated with each channel, and was full of methods that had to be implemented to catch errors, consumed messages, et cetera.

The current AMQP-CPP library uses C++11 features like lambda's and std::function callbacks instead of this ChannelHandler interface. The ChannelHandler no longer exist.

I've just updated the README file, and a couple of docblocks in the code to remove the last references to the ChannelHandler.

**Comment by willnige** [comment]
Thanks
