### ISSUE TITLE
libssl handling question

### ISSUE THREAD

**Issue by pabigot** [CopernicaMarketingSoftware/AMQP-CPP#219]
Using current master when attempting to use amqps in my Linux application I get an error:

    Secure connection cannot be established: libssl.so cannot be loaded

The executable is linked with `-lssl`, but because nothing in `libamqpcpp.so` or my application includes an unresolved reference satisfied by that library the reference is not retained by the linker and the library is not opened when the application starts.

It seems AMQP-CPP is implemented to support openssl only if something else in the process has already opened the shared library.  This is not a practice I've encountered before except in very unusual circumstances.

Is there a reason why this dependency is required to be dynamic?  A reason I can imagine is so an installed library can work on systems that both do and do not have openssl (assuming the application is coded to cooperate).  Is that a required use case for AMQP-CPP?

**Comment by EmielBruijntjes** [comment]
It is a very uncommon/weird architecture indeed. It’s because we built amqp-cpp for an an application that we try to ship with as little system dependencies as possible. If a user does not need amqps://, we want it to work, even if there is no openssl on the system available.

Secure connections are covered in the readme file: you can either link with -lssl (but remember to call ssl_library_init() in your application before you construct the connection object), or you can call dlopen() in your application to load openssl.

**Comment by pabigot** [comment]
Makes sense; I'd originally thought just linking would be enough to get encrypted connections to work (by doing a default init on demand), but can see that would lead to a configuration API that doesn't belong in this library.
