### ISSUE TITLE
What to do on connection loss

### ISSUE THREAD

**Issue by surgura** [CopernicaMarketingSoftware/AMQP-CPP#253]
What is the preferred method for graceful shutdown when the TCP connection is lost? E.g. should one call `close`?

I am thinking of a few issues I would like to solve nicely on connection loss:
- Publisher confirms / channel get callbacks that they failed and are closed
- Consume closes properly

I've  been using this library for quite some time, but actually never needed this functionality. I'm not sure if this is missing in documentation or if I can't read.

**Comment by EmielBruijntjes** [comment]
Have you been testing with this? As far as I remember, if you're using the AMQP::TcpConnection and AMQP::TcpChannel classes, this is all being taken care of by the TCP layer inside AMQP-CPP. It will make sure that your TcpHandler::onError() method is called. Inside this method you can do some application-specific cleanup. It is normally not useful to call more methods on either the connection or channel objects, because the connection is gone anyway.

If you take care of your own TCP handling (and you're using AMQP::Connection and AMQP::Channel directly) you have to do this yourself. Once you notice that reading from the socket fails because it is no longer connected, you know that the connection is gone and you can start cleaning in up application specific things. In that case you may call connection::close(), but it is not very useful, because there is no more TCP connection active that can be used to send a closing-handshake.

**Comment by surgura** [comment]
Ah yes, I'm implemented my own TCP handling. So on connection loss I will have to manually handle everything? I think it would be useful to add 'AMQP::Connection::ForceClose' that hard closes the connection without attempting anymore communication with the server. This would then call the error callbacks of open requests. For example (taken from the readme.md):

``` c++
channel.commitTransaction()
    .onSuccess([]() {
        // all messages were successfully published
    })
    .onError([](const char *message) {
        // none of the messages were published
        // now we have to do it all over again
    });
```

What do you think?

**Comment by EmielBruijntjes** [comment]
When I read the code, I see that there might indeed be an inconsistency in the library. When something unexpected happens (for example when the server sends an invalid frame to the client) for all operations and channels the onError callbacks are nicely called, and then the ConnectionHandler::onError() gets called too.

But when the connection is lost (which is just as bad), it seems that the operation-specific onError callbacks are ignored, and only the TcpHandler::onError() method is called (if you make use of the TCP module). This is not consistent.

If you're taking care of your own TCP handling, then the only way to handle this is to destruct the channel and connection objects. But this will not (as I read it now) trigger the onError callbacks for the incomplete operations.

But it requires some testing and better code inspection to know this for sure. I would say: if someone prematurely destructs the connection object, there should indeed be a way to force-error all running operations.

**Comment by EmielBruijntjes** [comment]
We have added a Connection::fail() to report an error on all open operations, and a TcpConnection::close(true) to force-close the connection without completing the handshake. The first one is useful if you have implemented your own TCP handling. Is this helpful?

**Comment by surgura** [comment]
That seems useful, yes. Does it call error callbacks and that kind of stuff?

**Comment by EmielBruijntjes** [comment]
Yes it does. It calls the onError() and onFinalize() method for all operations that were still running.
