### ISSUE TITLE
Message ack not working in my sample app

### ISSUE THREAD

**Issue by jhugard** [CopernicaMarketingSoftware/AMQP-CPP#28]
Writing a sample app using WinSock, but messages are remaining in the RabbitMQ queue even after being ack'd.  Any idea what I've done wrong?

https://github.com/jhugard/AMQP-CPP/blob/win-test/win/Test_AMQP-CPP/Test_AMQP-CPP.cpp

see line ~68.

**Comment by EmielBruijntjes** [comment]
I don't know if this is the cause or not, but in your "onData()" method in the winsockethandler class, you have the following loop:

````c++
		do
		{
			data += iResult;
			iResult = send(m_socket, data, static_cast<int>(size), 0);
		} while (iResult != SOCKET_ERROR && (sent += iResult) < size);
````

That is not a very smart implementation (and might even be wrong). When not all data can be sent, it is better to buffer the data, include the socket in the select() loop and wait for it to become writable again. Only when select() reports that the socket is writable, you should send the buffered data. 

With your current implementation, you create a crazy CPU intensive loop when not all data could be delivered at once. And the system may not even able to empty its internal buffers (so that the next call to send() _will_ succeed) because it is so busy running your loop.

**Comment by jhugard** [comment]
Changed the write to use a blocking select w/15 second timeout, but still has the same problem.  :-1: 
(new code pushed to my repo)

**Comment by EmielBruijntjes** [comment]
I don't have a Windows system here, so I am not in a position to help. channel.ack() does work, we use it all the time in our MailerQ application. So the error is probably inside your code -- but I cannot guarantee that, maybe the AMQP-CPP library has a bug when compiled on a Windows platform...

**Comment by jhugard** [comment]
Yah, pretty sure its in my code but after a few hours couldn't spot it.  Will continue to dig when I have time: don't have a project right now, just learning-up on RabbitMQ.
