### ISSUE TITLE
Suspicious code

### ISSUE THREAD

**Issue by shlyakpavel** [CopernicaMarketingSoftware/AMQP-CPP#304]
https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/5a648fe2d8df7dacc389fdc83be5d35e616a06c1/src/receivedframe.cpp#L315-L316
It looks much like a copy-paste mistake. 
According to rabbitmq specification 
Type 4 is for "OOB­METHOD"
Type 8 is for "HEARTBEAT"
However, they are processed with the same function. Is it normal? Is the "out of band" mode implemented?

**Comment by mvdwerve** [comment]
This library implements [AMQP 0.9.1](https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf) which states `Type = 4, "HEARTBEAT": heartbeat frame.`. I think 8 was the old frame type, which is why it was kept in there. Also see [0.8 to 0.9.1](https://www.rabbitmq.com/amqp-0-8-to-0-9-1.html) from RabbitMQ.
