### ISSUE TITLE
AMQP::Message Question...

### ISSUE THREAD

**Issue by theWizK** [CopernicaMarketingSoftware/AMQP-CPP#31]
I am curious if when my MessageCallback implementation gets called, if i am responsible for trimming the message.body() to the correct size using message.bodySize().  The reason I ask, is because often the char* returned from message.body() is not terminated at the message.bodySize() length and I sometime get gibberish and / or partial message bodies from previous messages unless I "trim" the message body myself.

Thanks.

**Comment by EmielBruijntjes** [comment]
You should use the bodySize() method. 

Nothing from the AMQP standard forbids message bodies from containing binary data. You can for example use RabbitMQ to queue PDF documents, images, mp3 files or anything else that comes in binary format. This binary data may be full of null characters, and there is also no guarantee that the last character is a null. That's why you need the bodySize() method to find the size.

**Comment by theWizK** [comment]
Excellent, thanks for the response!  This is how I used the API; I just wanted to make sure that was the expected usage and I wasn't missing something more obvious.
