### ISSUE TITLE
Polling scheme?

### ISSUE THREAD

**Issue by emerth** [CopernicaMarketingSoftware/AMQP-CPP#341]
AMQP-CPP, it's examples and docs, seems to be very strongly built around an event loop. I cannot see any way around the monitor() method of the Handler - type classes.

If it can be used to connect to an AMQP server, check for messages in a queue, thus in a polling manner, could you mention the name of a method or class that I could start investigating?

I know this is not a school, but I didn't write AMQP-CPP, so I do not know it like the back of my hand...

Thanks!

**Comment by EmielBruijntjes** [comment]
You should think in this direction:

- Create an event loop (for example a libev instance), and wrap that inside the LibEv handler-implementation that is provided by AMQP-CPP (you can also use other event loops, but this one is simple to integrate because it comes with AMQP-CPP).
- Make a connection to rabbitmq using AMQP::TcpConnection and your handler
- Create an AMQP::Channel
- Call all the methods on the channel object to do whatever you want (like checking a queue).
- In your callbacks you store all the information that you receive somewhere (like inside a member variable, or maybe even inside global variables? Whatever suits you).
- Destruct the channel object, and call connection.close().
- Run the event loop. This will block for a while, while AMQP-CPP connects to rabbitmq, sends the instructions, receives the responses, calls your callbacks and closes the connection.
- When the loop comes to an end, it means that all operations are ready. You can now inspect the variables in which you had stored the received data.
- Destruct the connection, handler and event loop.

Good luck.

**Comment by emerth** [comment]
I'll look at that. Thank, Emiel!
