### ISSUE TITLE
publish success or not

### ISSUE THREAD

**Issue by dronord** [CopernicaMarketingSoftware/AMQP-CPP#346]
Hola!
How to determine success of publish?
onSuccess() - silent
onError() - silent, even on wrong route key.
Thank you.

**Comment by tarhan** [comment]
There no concept of "wrong routing key" in AMPQ because binding between exchange and queues occurs dynamically.  
Any unrouted messages vanishes.

In case of RabbitMQ broker you have option called [Alternate Exchanges](https://www.rabbitmq.com/ae.html). So for example for your `my_exchange_for_app_1` you can declare **alternate exchange** called `my_unrouted_exchange_for_app_1`. And all unrouted messages goes to there. Of course to be sure that messages not vanished from there also you should declare **alternate exchange** as `fanout` type and bind as least one queue to it.

**Comment by EmielBruijntjes** [comment]
What @tarhan says. A publish with "a wrong key" is not a failure. It is in fact for many publish/subscribe scenarios quite useful. Example: your application publishes realtime information about the state of the system so that users can monitor it. When nobody is monitoring, this information is discarded. But once a user logs on, a (temporary private) queue is created by that user and bound to the exchange to receive this realtime data. If two users log on, a second queue is created and bound (et cetera).

It would however be an error if a published message is lost because of (for example) a crash of RabbitMQ. If you detect that the TCP-connection is suddenly lost, how can you be sure whether the message that you had just sent a fraction of a second before was already received and handled? T
