### ISSUE TITLE
Error Handling Question...

### ISSUE THREAD

**Issue by theWizK** [CopernicaMarketingSoftware/AMQP-CPP#36]
More of a general best-practice question than an issue anyone needs to address.  With this library should I assume that an onError() callback that comes from any channel operation should render the channel as in an error state and require my library to reset the channel before re-using it?  I think this is what the documentation is referring to, and I have some error handling on startTransaction method's Deferred object, but not on some of the other operations that happen inside the transaction.  Should this capture all errors that happen in the scope of the transaction, or should I also somehow mark the channel invalid and reset it on consume() calls happening in the scope of a transaction?  I have an application currently that periodically (sporradic / every few days maybe) gets some sort of a (channel) error which leaves the channel (and message manager object I have wrapping the channel) in a state where it's no longer consuming messages.  The pseudo logic is:

loop while connected and not channelError flag
  try:
    if (!connected || channelError)
    start a transaction (onError, flag channel as error state internally, rollback transaction)
      consume a message (onError, just log the error, rollback transaction)
        onReceived - do something
        onError - log the error; rollback transaction
   commit transaction; continue loop if still connected and thread:isRunning flag set
  catch:
    log error; rollback transaction    
   if (channelError) -- close channel, reset channel, clear cannelError
end loop

given this very general sequence, is setting the channelError flag only on the transaction onError() handler sufficient, or do I need to also do it in any of the other places I implement logging of the error only now?   Just curious on where some of your implementations do clean up of any errors and reset / re-create the channel...

Thanks.

**Comment by EmielBruijntjes** [comment]
I'm not exactly sure what your question is, because you're addressing multiple topics. But I still hope the following answer does clear things up for you.

When an error occurs on a channel, the entire channel becomes invalid, and from that moment on it can no longer be used for sending further instructions to RabbitMQ. This is how the AMQP protocol works. However, setting up a channel is, as far as I know, not a very expensive operation, so you can create many different channels. If you're sending multiple unrelated commands (for example because your application is consuming from one queue, while publishing to another, or because it is publishing to many different queues), you can very well use all different channels. You can even create a new channel for every new published message. By doing this, you ensure that an error with one published message will not affect any of the other operations, because they're all sent over different channels. You do not even have to keep the channel object into scope when it is being used, so you can simple create a Channel object on the stack, and use it for an instruction and have the channel object be destructed even before an answer comes back.

````c++
void createNotSoImportantQueue(AMQP::Connection *connection)
{
    // create a temporary channel on the stack just for the next "declareQueue" call, so
    // that any errors that occur with it have no influence on all the other operations that 
    /// are going on
    AMQP::Channel channel(connection);

    // declare the queue (we don't check for errors because it is not really a problem if the
    // operation fails (the queue is not important) and we do it on a a seperate channel so
    // it will not interfere with other operations
    connection.declareQueue(...);
}
````

In the AMQP-CPP library, you can install error handlers on almost every operation. Most operations return some sort of "Deferred" object, that allow you to set an "onError(...)" callback. When an error occurs, this callback function will automatically be called by the AMQP-CPP library. Besides this operation-specific error callback, you can also install an error handler callback on the entire channel. This is just an other approach for setting up an error handler: when an error occurs, both functions
are called: the operation-specific set via the Deferred object, and the channel specific callback. You probably only need to install one of them.

About transactions: transactions in RabbitMQ work not the same as in databases, and in many cases you do not need them. See also https://www.rabbitmq.com/semantics.html. Transactions for consuming is (afaik) also without meaning. I have implemented transactions in AMQP-CPP because I wanted it to be complete, but in reality I never use them. And in your setup, I doubt wheter you really need them.

Does this makes things more clear?

**Comment by theWizK** [comment]
Yes, thanks for the clarification!
