### ISSUE TITLE
Need Delivery Tag ID of published message for book keeping

### ISSUE THREAD

**Issue by rahimkanji** [CopernicaMarketingSoftware/AMQP-CPP#391]
Need Delivery Tag ID of published message for book keeping and redeliver that message in case it's lost or nacked by RabbitMQ

**Comment by EmielBruijntjes** [comment]
You can use publisher-confirms for that. 

## Low level
Use Channel::confirmSelect().onAck(...).onNack(...) to install callbacks when your published messages are acked or nacked by RabbitMQ. You have to keep a counter yourself

## Abstraction layer
You can also wrap your channel in an AMQP::Reliable object, so that the AMQP-CPP automatically tracks your messages.
```
AMQP::Reliable reliable(channel);
reliable.publish(...).onLost(your_handler_if_message_was_lost)
```
