### ISSUE TITLE
PassthroughBuffer move and copy constructors

### ISSUE THREAD

**Issue by skaae** [CopernicaMarketingSoftware/AMQP-CPP#418]
I'm reading through the source code and have a few questions.

I think there is a typo in the copy and move constructor of Passthroughbuffer`? 

https://github.com/CopernicaMarketingSoftware/AMQP-CPP/blob/1dc169810d31110e134fbe032be009f5f8e98d73/src/passthroughbuffer.h#L111-L126

My understanding of The PassThroughBuffer is that is constructed on the stack and that the buffer is flushed when the buffer is destructed? Is the flush on destruct normal practice it took me a while to figure out ? 
Wouldn't it be more efficient if ConnectionImpl owned a buffer that was reused?

**Comment by EmielBruijntjes** [comment]
I honestly don't know. The responsibility of PassthroughBuffer is to make sure that we do not pass many (small) buffers to "user space", but that we bundle small writes into bigger operations of 4096 bytes per call. This is the task of the PassthroughBuffer::append() method. The destructor then takes care of the final batch. By using a stack-based class with a destructor we use a trick to ensure that we never forget to send out the remaining bytes (because the destructor runs automatically).

I don't know if a member-variable would be more efficient, and if it is, I do I know whether this would be a significant improvement in the total performance of the library.

What is the typo you're referring to?

**Comment by skaae** [comment]
Thanks for the explanation it makes sense. 

>>What is the typo you're referring to?

The copy and move constructor of passthroughbuffer takes `CopiedBuffer` as argument, I'm not sure that on purpose?

**Comment by EmielBruijntjes** [comment]
You were right about that, it is a typo indeed.
