### ISSUE TITLE
warning: converting ‘AMQP::Table’ to a reference to the same type will never use a type conversion operator

### ISSUE THREAD

**Issue by vss888** [CopernicaMarketingSoftware/AMQP-CPP#446]
Compiling a test application with gcc-11.2.0:
`g++ -std=c++17 -lamqpcpp -lpthread -ldl`
produces the following warnings:
```
In file included from .../AMQP-CPP-4.3.15-gcc11.2.0/include/amqpcpp.h:56,
                 from Test.C:8:
.../AMQP-CPP-4.3.15-gcc11.2.0/include/amqpcpp/table.h:271:13: warning: converting ‘AMQP::Table’ to a reference to the same type will never use a type conversion operator [-Wclass-conversion]
  271 |     virtual operator const Table& () const override
      |             ^~~~~~~~
In file included from .../AMQP-CPP-4.3.15-gcc11.2.0/include/amqpcpp.h:57,
                 from Test.C:8:
.../AMQP-CPP-4.3.15-gcc11.2.0/include/amqpcpp/array.h:235:13: warning: converting ‘AMQP::Array’ to a reference to the same type will never use a type conversion operator [-Wclass-conversion]
  235 |     virtual operator const Array& () const override
```
The warnings are very reasonable: why having an operator which converts an object to the same type?

**Comment by EmielBruijntjes** [comment]
That's because of the architecture of the library. My intention was to make tables accessible via [] operators, and every type of field needs to implement a certain interface in case it is ever called as if it was a table (to deal with tables that are nested in tables). This works as intended (afaik) but a later version of the compiler started showing this warning because of the chosen implementation. 

Maybe I fix it some day, but it does right now not have much priority. If you want you can of course have a look at it and send in a pull request.
