### ISSUE TITLE
Question: libevent vs libev vs libuv in AMQP-CPP

### ISSUE THREAD

**Issue by vss888** [CopernicaMarketingSoftware/AMQP-CPP#447]
Unfortunately, [GitHub Discussions](https://docs.github.com/en/discussions) is not [enabled ](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) for this repository. So, sorry, for using Issues to ask a question.

I have noticed that (as of the time of this writing) the last commit times are the following:

- libev.h : 7 hours ago
- libevent.h : 4 years ago
- libuv.h : 4 years ago

Could you please let me know which one it is a reflection of:

1. libev.h implementation was found to be the most useful one and therefore is still under active development and improvement, while libevent.h and libuv.h were found to be inferior in some way and so are no longer actively developed
2. libevent.h and libuv.h are in a mature and stable state and so no longer need changes and fixes, while libev.h still has a lot of unresolved issues and so is still actively developed

I.e. which one would you recommend to be used in a new project?

Thank you!

**Comment by EmielBruijntjes** [comment]
The AMQP-CPP library is event-loop agnostic. As long as you implement the "ConnectionHandler" interface, you can integrate it with any event loop, whether you're doing select() or poll() calls yourself, or whether you use a library for it like libuv or libevent.

For _convenience_ reasons I and some other people already wrote a number of classes that do exactly this. The libevent.h header file contains the class that implements the ConnectionHandler to work in combination with libevent. Same for libev.h and libuv.h. At Copernica we use, for historic reasons, libev. That's why the libev.h class is updated (way) more frequently than the others - because that's the that _we_ use.

However, if I had to choose an event library today for a new application, I would not go for libev.

So to answer your question: it depends.
