### ISSUE TITLE
question: how to use AMQP-CPP in a multithreaded program?

### ISSUE THREAD

**Issue by vss888** [CopernicaMarketingSoftware/AMQP-CPP#450]
I have bumped today into the following comment while opening a bug report in this repository (this comment should be part of introduction to AMQP-CPP IMHO):

**_"Watch out: do not use threads! AMQP-CPP objects are not thread-safe _by design_. If you construct channels or call methods from one thread, while the event loop is running in a different thread, unexpected things can and will happen."_**

Well, I do have multiple threads in my program and each of them needs to send messages to RabbitMQ once in a while. So, my question is if it is possible to use AMQP-CPP in such situation?

Since I can not run the event loop in a parallel thread, the only thing that comes to my mind is to: 
- have a global AMQP-CPP mutex
- lock it every time I need to do something through AMQP-CPP
- since, it seems, that it is `connection.close()` (for example, `AMQP::TcpConnection connection`) that breaks the event loop, I have to 1) create a new connection, 2) send messages, 3) close the connection, 4) run the event loop - and all of these need to be done every time I need to send any messages.

I do not see a smarter way to publish messages once in a while even in a single threaded program. The call to running an event loop (for example, `uv_run(loop, UV_RUN_DEFAULT)`) blocks unless I close the connection, so the steps 1,2,3,4 above have to be repeated to send a message even in this case.

Is there any smarter way to send messages using AMQP-CPP to RabbitMQ from a single or multiple threads?

Thank you very much for your help!

**Comment by EmielBruijntjes** [comment]
It is not so much different with other things, isn't it? You also don't write to the same file from multiple threads, or write to the same memory buffer from multiple threads. If you do so, you will corrupt your files or your memory. The same happens if you write to the same amqp connection from multiple threads.

There are ways to synchronize threads so that you can hand over data from one thread to the other. Programs can also have multiple event loops, for example one in every thread. One thread is then responsible for the AMQP connection and whenever you need to publish something you synchronize the threads and hand over the instruction to the AMQP thread.

**Comment by vss888** [comment]
@EmielBruijntjes
Emiel, thank you for your reply! Could you please clarify your suggestion: should I run an event loop in one thread and do all the `publish` calls from another **_single_** thread? This way all the writes to the ampq connection would be done from a single thread. Is this a right way to work in AMQP-CPP?

**Comment by EmielBruijntjes** [comment]
I cannot answer that question. That is really up to you as application developer and software architect. Is the AMQP connection the bottleneck in CPU processing? Or is your main thread so busy that it cannot keep up with the AMQP traffic? Then put it in a thread of its own. But is your application not at all CPU bound, then why bother with threads in the first place?

In most AMQP applications that I write, I do not use threads because the main thread can do it all. Those application are often mainly IO-bound, or most of the time idle waiting for messages. However, I also have applications in which the AMQP traffic or the CPU processing is so heavy that I even run multiple threads, sometimes even multiple threads that all have their own AMQP connection.

**Comment by vss888** [comment]
@EmielBruijntjes 
Emiel, of course, you are right - I am the one responsible for the decisions in my code. All I am asking is for **_any_** advice on how to set up code using AMQP-CPP that it would not crash, and so far AMQP-CPP crashes on me all the time no matter what I do in my tests. 

I can not conceptually wrap my head around of how to combine the requirements of 
- having to call a blocking function `uv_run(loop, UV_RUN_DEFAULT)`,
- not be allowed to run the function in a separate thread,
- having a need to call AMQP-CPP methods (`publish` in my case) frequently, 

unless all of the `"connection => channel => publish => disconnect => run loop"` steps are repeated every time I need to publish something. I can see how the above requirements are OK for a program processing messages _indefinitely_ since it is possible to set up `onReceived` callback, but I do not see how one can do it for publishing, unless `publish` methods are not supposed to be called by the user and messages are supposed to be put to some "to-publish" queue instead (and the queue is monitored by the event loop).

I have switched to the safest way possible (with the exception of repeating the whole setup for every message), i.e. 

1. single AMQP-CPP connection and single channel are setup, 
2. then I start the event loop in a parallel thread, 
3. then all I do is to call `publish` methods locking a single mutex (so no `publish` calls happen in parallel)

and AMQP-CPP still crashes.

**Comment by EmielBruijntjes** [comment]
Maybe you do not realize that you should do more in a thread than just handling the AMQP connection? This is essentially what you do in the AMQP-CPP thread:

- create an event loop
- register the AMQP-CPP connection on it
- register a synchronize-watcher to wake up the other thread (I think libuv has things like synchronize-watchers or so)
- create a queue (for example std::queue) with instructions that have to be picked up by the amqp-thread
- add a mutex to this queue
- start the thread in which the event loop runs

You thread is now responsible for two things: the AMQP connection **plus** monitoring whether other threads have instructions for it. When you want to send something to RabbitMQ from one of the other threads in your program, you do this:

- Lock the mutex
- Add the instruction to the std::queue
- Unlock the mutex
- Wakeup the AMQP thread using the synchronize-watcher

In the AMQP thread, when the callback of the synchronize watcher is called, you can do the following:

- Lock the mutex
- Read out the instructions from the std::queue
- Unlock the mutex
- Execute the instructions

Inside the std::queue you can even use std::function objects, giving you max flexibility over what you can do with the AMQP connection.
