### ISSUE TITLE
Q: What is the correct way to run in multithreading env

### ISSUE THREAD

**Issue by matwey** [CopernicaMarketingSoftware/AMQP-CPP#520]
Hello,

I apology creating the issue here because there are no links to community support in the README.

What I am trying to do. I use the `libboostasio` handler to run multi-threading consumer. I created N channels consuming the same queue and started `io_context.run()` in N+1 threads. So far so good, but I've found that `onReceived()` callbacks are executed only in one thread at the same time. It is an issue for me, because my callbacks do some heavy job. I would like this job to be done in parallel but I efficiently have single-thread consumer currently.

I would like somebody to confirm that it is expected behavior, because README says nothing about `onReceived()` callback should not block.

**Comment by EmielBruijntjes** [comment]
If you need to do some heavy lifting by the consumer, and you do not mind that this blocks other amqp operations, you can just do that without any worries (but do make sure that you disable the heartbeats so that the rabbitmq server does not break the connection because of inactivity).

If you want the application to stay responsive during the cpu intensive operations, start a new thread and do the work there. That is just standard c++ stuff for which you can fibd examples everywhere.

Anyway, amqp-cpp objects (like almost all classes in c++) are not thread safe. You cannot consume in one thread and do something else with the same connection in a different thread.

**Comment by matwey** [comment]
> If you need to do some heavy lifting by the consumer, and you do not mind that this blocks other amqp operations, you can just do that without any worries (but do make sure that you disable the heartbeats so that the rabbitmq server does not break the connection because of inactivity).
> 
> If you want the application to stay responsive during the cpu intensive operations, start a new thread and do the work there. That is just standard c++ stuff for which you can fibd examples everywhere.
> 

This is exactly what I am doing on top of Boost ASIO.

> Anyway, amqp-cpp objects (like almost all classes in c++) are not thread safe. You cannot consume in one thread and do something else with the same connection in a different thread.

Do you mean that writing to **different** channel objects isn't thread-safe too?

**Comment by EmielBruijntjes** [comment]
If the channels all use the same connection, it is indeed not thread safe. If you use a different connection in each thread it is ok.

**Comment by matwey** [comment]
Thanks, I see now. Bad news is that current `LibBoostAsioHandler` implementation is unusable in multi-threading environment.

**Comment by EmielBruijntjes** [comment]
I don't know about that (and whether it is true) - but that is outside of the scope of AMQP-CPP
