### ISSUE TITLE
asio.hpp can't be found.

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#57]
When I build the example, I can not find the file "asio.hpp" which is included in the file "asiohandler.h", any suggestions?

**Comment by alexandrebl** [comment]
You need to install Boost Library. You can find in this link: http://www.boost.org/

**Comment by xupanwilson** [comment]
I have installed boost, Now I have the following compile problem with the steps in the following:
I goto the folder [AMQP-CPP/examples/rabbitmq_tutorials]
1.cmake .
2.make

the output has a lot of errors such as:
/usr/include/amqpcpp/array.h:97:31: error: 'ptr' was not declared in this scope
             _fields.push_back(ptr);
                               ^
/usr/include/amqpcpp/array.h:102:30: error: 'ptr' was not declared in this scope
             _fields[index] = ptr;

Seems the CMakeLists.txt has some problems, maybe need to change the content of  "include_directories"

Any suggestions?

**Comment by alexandrebl** [comment]
I've been using g++ 5/gcc 5 to compile this library with -lboost_system and -lboost_filesystem in compiler options.

**Comment by EmielBruijntjes** [comment]
I am closing this issue. The boost-asio example does not come from me, and I am not so familiar with boost so I don't know how to fix it. It would be helpful if anyone could send in a pull request to solve these issues, otherwise I am going to remove this example as it seems to generate more questions than it answers.
