### ISSUE TITLE
QT integration

### ISSUE THREAD

**Issue by mridulwebengineer** [CopernicaMarketingSoftware/AMQP-CPP#88]
I want to use this inside my QT application. Please help me .

**Comment by tiaanwessels** [comment]
There is a problem to integrate with Qt. The method name emit is used by AMQCPP but also by Qt

**Comment by tiaanwessels** [comment]
There is a problem to integrate with Qt. The method name emit is used by AMQCPP but also by Qt. You get compile errors:
../../include/adhoc/amqpcpp/deferredconsumerbase.h:89:31: error: expected ‘)’ before ‘&&’ token
virtual void emit(Message &&message, uint64_t deliveryTag, bool redelivered) const = 0;
due to the emit
To solve I had to edit AMQPCPP sources and change all emit to emitm which solved it for me.

**Comment by EmielBruijntjes** [comment]
I think you safely can since the latest commit
