### ISSUE TITLE
How can I get the consumer count on a specific queue?

### ISSUE THREAD

**Issue by xupanwilson** [CopernicaMarketingSoftware/AMQP-CPP#89]
I am using the rpc mode, if the server is down, the queue is still exist, then the client will send a lot requests to the server queue. When the server is up, it will do some useless work as the client is no more exist.

I don't want the client to send request any more. In the Java client, I can get the consumerCount, if the consumerCount is zero, means the rpc server is down. If there is such a method in the C++ interface?

**Comment by Kojoley** [comment]
Why not just use `auto-delete` or `exclusive` queue for the server?

There is no mechanism to notify you about consumer count change. You can obtain consumer count only when declaring a queue. It will be overkill to make a such call before considering if you should send the data or not. And if you are going to cache this value by making such call with timer, so you either will still send some data to the queue when there is no consumers, or you will discard sending data, because of timer and latency.
